### ISSUE TITLE
Not an issue but proposal

### ISSUE THREAD

**Issue by alienatedsec** [RichardL64/Solar#2]
Combine your project with mine and you will have both projects/solutions in tandem.
https://github.com/alienatedsec/solis-ha-modbus-cloud
Happy to work together on this.

**Comment by RichardL64** [comment]
Hi, thanks for getting in touch, your project looks interesting but much more involved than mine.

My direction is a very lightweight scalable interface to let IOT style devices - Shelly or Wemos/Arduino to query and act on the state of the inteverter/solar/battery setup.

No servers - not even Home Assistant local, but absolute minimum of off the shelf components, minimum of code layers (ideally no O/S)

By all means re-use anything on this project -  much of it is leveraged and built on knowledge from elsewhere anyway. Drop a credit or a link if it makes sense.

Also happy to share notes with you or anyone.

Good luck with your project.
